server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aacv?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: l123578964
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  session:
    jdbc:
      initialize-schema: always
    timeout: 30m
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    com.aacv: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO