package com.aacv.system.shared.domain;

public enum ErrorCode {
    VALIDATION_FAILED,
    AUTHENTICATION_REQUIRED,
    SESSION_EXPIRED,
    INVALID_CREDENTIALS,
    ACCOUNT_DISABLED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    RESOURCE_CONFLICT,
    USERNAME_CONFLICT,
    VERSION_CONFLICT,
    CSRF_INVALID,
    GRAPH_UNAVAILABLE,
    GRAPH_QUERY_TIMEOUT,
    GRAPH_REBUILD_IN_PROGRESS,
    EXPORT_LIMIT_EXCEEDED,
    EXPORT_CONCURRENCY_LIMIT,
    EXPORT_EXPIRED,
    INTERNAL_ERROR
}
